config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :authors

      resources :recommendations

      resources :reviews

      resources :books

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "books#index"
  resources :authors
  resources :recommendations
  resources :reviews
  resources :books
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  # Direct associations

  belongs_to :recipient,
             class_name: "User",
             foreign_key: "sender_id"

  belongs_to :sender,
             class_name: "User",
             foreign_key: "body"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    created_at
  end
end

app/controllers/api/v1/recommendations_controller.rb
class Api::V1::RecommendationsController < Api::V1::GraphitiController
  def index
    recommendations = RecommendationResource.all(params)
    respond_with(recommendations)
  end

  def show
    recommendation = RecommendationResource.find(params)
    respond_with(recommendation)
  end

  def create
    recommendation = RecommendationResource.build(params)

    if recommendation.save
      render jsonapi: recommendation, status: :created
    else
      render jsonapi_errors: recommendation
    end
  end

  def update
    recommendation = RecommendationResource.find(params)

    if recommendation.update_attributes
      render jsonapi: recommendation
    else
      render jsonapi_errors: recommendation
    end
  end

  def destroy
    recommendation = RecommendationResource.find(params)

    if recommendation.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: recommendation
    end
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: %i[show edit update destroy]

  def index
    @q = Recommendation.ransack(params[:q])
    @recommendations = @q.result(distinct: true).includes(:sender,
                                                          :recipient).page(params[:page]).per(10)
  end

  def show; end

  def new
    @recommendation = Recommendation.new
  end

  def edit; end

  def create
    @recommendation = Recommendation.new(recommendation_params)

    if @recommendation.save
      message = "Recommendation was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @recommendation, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @recommendation.update(recommendation_params)
      redirect_to @recommendation,
                  notice: "Recommendation was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @recommendation.destroy
    message = "Recommendation was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to recommendations_url, notice: message
    end
  end

  private

  def set_recommendation
    @recommendation = Recommendation.find(params[:id])
  end

  def recommendation_params
    params.require(:recommendation).permit(:body, :sender_id, :recipient_id)
  end
end

app/views/recommendations/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Recommendation #<%= recommendation.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Body</dt>
      <dd>
        <% if @recommendation.sender.present? %>
          <%= link_to recommendation.sender, recommendation.sender %>
        <% end %>
      </dd>

      <dt>Sender</dt>
      <dd>
        <% if @recommendation.recipient.present? %>
          <%= link_to recommendation.recipient, recommendation.recipient %>
        <% end %>
      </dd>

      <dt>Recipient</dt>
      <dd><%= recommendation.recipient_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back recommendation, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_recommendation_url(recommendation), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to recommendation, method: :delete, data: { confirm: "Do you really want to delete this recommendation?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(recommendation.updated_at) %> ago
  </div>
</div>

app/views/recommendations/_form.html.erb
<% was_validated = recommendation.errors.any? %>

<%= form_with(model: recommendation, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% body_class = "form-control" %>
    <% body_was_invalid = recommendation.errors.include?(:body) %>

    <% if was_validated %>
      <% if body_was_invalid %>
        <% body_class << " is-invalid" %>
      <% else %>
        <% body_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :body %>
    <%= f.collection_select :body, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if body_was_invalid %>
      <% recommendation.errors.full_messages_for(:body).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% sender_class = "form-control" %>
    <% sender_was_invalid = recommendation.errors.include?(:sender) %>

    <% if was_validated %>
      <% if sender_was_invalid %>
        <% sender_class << " is-invalid" %>
      <% else %>
        <% sender_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :sender_id %>
    <%= f.collection_select :sender_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if sender_was_invalid %>
      <% recommendation.errors.full_messages_for(:sender).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% recipient_class = "form-control" %>
    <% recipient_was_invalid = recommendation.errors.include?(:recipient) %>

    <% if was_validated %>
      <% if recipient_was_invalid %>
        <% recipient_class << " is-invalid" %>
      <% else %>
        <% recipient_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :recipient_id %>
    <%= f.number_field :recipient_id, class: recipient_class, placeholder: "Enter recipient" %>
    <% if recipient_was_invalid %>
      <% recommendation.errors.full_messages_for(:recipient).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/recommendations/_list_item.html.erb
<%= link_to recommendation, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= recommendation %>
    <small class="text-muted">
      <%= time_ago_in_words(recommendation.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/recommendations/_recommendations_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "recommendations_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :recipient_id, "Recipient" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :recipient_id_gteq, :class => "form-control", :placeholder => "Recipient greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :recipient_id_lteq, :class => "form-control", :placeholder => "Recipient less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :sender_email_cont, "Sender email contains" %>
    <%= f.text_field :sender_email_cont, :class => "form-control", :placeholder => "Sender email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :recipient_email_cont, "Recipient email contains" %>
    <%= f.text_field :recipient_email_cont, :class => "form-control", :placeholder => "Recipient email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/recommendations" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#recommendations_filters">
  Show filters
</a>

app/views/recommendations/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Recommendation #<%= @recommendation.id %>
      </h2>

      <div class="card-body">
        <%= render "form", recommendation: @recommendation %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recommendations/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Recommendations

      <%= link_to new_recommendation_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "recommendations/recommendations_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Recommendations

        <%= link_to new_recommendation_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @recommendations, partial: "list_item", as: :recommendation %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @recommendations, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/recommendations/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Recommendation
      </h2>

      <div class="card-body">
        <%= render "form", recommendation: @recommendation %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recommendations/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @recommendation, partial: "card", as: :recommendation %>
  </div>
</div>