config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :authors

      resources :recommendations

      resources :reviews

      resources :books

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "books#index"
  resources :authors
  resources :recommendations
  resources :reviews
  resources :books
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  # Direct associations

  has_many   :books,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/authors_controller.rb
class Api::V1::AuthorsController < Api::V1::GraphitiController
  def index
    authors = AuthorResource.all(params)
    respond_with(authors)
  end

  def show
    author = AuthorResource.find(params)
    respond_with(author)
  end

  def create
    author = AuthorResource.build(params)

    if author.save
      render jsonapi: author, status: :created
    else
      render jsonapi_errors: author
    end
  end

  def update
    author = AuthorResource.find(params)

    if author.update_attributes
      render jsonapi: author
    else
      render jsonapi_errors: author
    end
  end

  def destroy
    author = AuthorResource.find(params)

    if author.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: author
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit update destroy]

  def index
    @q = Author.ransack(params[:q])
    @authors = @q.result(distinct: true).includes(:books).page(params[:page]).per(10)
  end

  def show
    @book = Book.new
  end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: "Author was successfully created."
    else
      render :new
    end
  end

  def update
    if @author.update(author_params)
      redirect_to @author, notice: "Author was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_url, notice: "Author was successfully destroyed."
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :book_id, :author_headshot)
  end
end

app/views/authors/_author_books.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Books

    <a data-toggle="collapse" href="#author_books_new_form">
      Add book
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @author.books.each do |book| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to book, book %>

        <%= link_to book, method: :delete, data: { confirm: "Do you really want to delete this book" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="author_books_new_form">
        <%= render partial: "authors/author_books_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/authors/_author_books_new_form.html.erb
<%= form_with(model: @book, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author %>

    <%= f.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>

    <%= f.text_field :genre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :page_length %>

    <%= f.text_field :page_length, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.text_field :user_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :author_id, value: @author.id %>

  <div class="form-group">
    <%= f.label :book_cover %>

    <%= f.file_field :book_cover, class: "form-control" %>
  </div>

  <%= f.submit "Create book", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/authors/_authors_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "authors_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :author_headshot_cont, "Author headshot contains" %>
    <%= f.text_field :author_headshot_cont, :class => "form-control", :placeholder => "Author headshot contains" %>
  </div>

  <div class="form-group">
    <%= f.label :book_id, "Book" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :book_id_gteq, :class => "form-control", :placeholder => "Book greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :book_id_lteq, :class => "form-control", :placeholder => "Book less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :books_name_cont, "Books name contains" %>
    <%= f.text_field :books_name_cont, :class => "form-control", :placeholder => "Books name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/authors" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#authors_filters">
  Show filters
</a>

app/views/authors/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Author #<%= author.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= author.name %></dd>

      <dt>Book</dt>
      <dd><%= author.book_id %></dd>

      <dt>Author headshot</dt>
      <dd><%= author.author_headshot %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back author, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_author_url(author), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to author, method: :delete, data: { confirm: "Do you really want to delete this author?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(author.updated_at) %> ago
  </div>
</div>

app/views/authors/_form.html.erb
<% was_validated = author.errors.any? %>

<%= form_with(model: author, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = author.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% author.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% book_class = "form-control" %>
    <% book_was_invalid = author.errors.include?(:book) %>

    <% if was_validated %>
      <% if book_was_invalid %>
        <% book_class << " is-invalid" %>
      <% else %>
        <% book_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :book_id %>
    <%= f.number_field :book_id, class: book_class, placeholder: "Enter book" %>
    <% if book_was_invalid %>
      <% author.errors.full_messages_for(:book).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% author_headshot_class = "form-control" %>
    <% author_headshot_was_invalid = author.errors.include?(:author_headshot) %>

    <% if was_validated %>
      <% if author_headshot_was_invalid %>
        <% author_headshot_class << " is-invalid" %>
      <% else %>
        <% author_headshot_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :author_headshot %>
    <%= f.text_field :author_headshot, class: author_headshot_class, placeholder: "Enter author headshot" %>
    <% if author_headshot_was_invalid %>
      <% author.errors.full_messages_for(:author_headshot).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/authors/_list_item.html.erb
<%= link_to author, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= author %>
    <small class="text-muted">
      <%= time_ago_in_words(author.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/authors/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Author #<%= @author.id %>
      </h2>

      <div class="card-body">
        <%= render "form", author: @author %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Authors

      <%= link_to new_author_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "authors/authors_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Authors

        <%= link_to new_author_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @authors, partial: "list_item", as: :author %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @authors, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/authors/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Author
      </h2>

      <div class="card-body">
        <%= render "form", author: @author %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @author, partial: "card", as: :author %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "authors/author_books" %>
  </div>
</div>